In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
consum = pd.read_excel(r"D:\AnalytixLabs\Case Studies\Machine Learning Case Studies\1. Capstone Case Study - Predict Cred Card Consumption\CreditConsumptionData.xlsx")

In [5]:
behave = pd.read_excel(r"D:\AnalytixLabs\Case Studies\Machine Learning Case Studies\1. Capstone Case Study - Predict Cred Card Consumption\CustomerBehaviorData.xlsx")

In [7]:
demo = pd.read_excel(r"D:\AnalytixLabs\Case Studies\Machine Learning Case Studies\1. Capstone Case Study - Predict Cred Card Consumption\CustomerDemographics.xlsx")

In [8]:
consum.head()

      ID  cc_cons
0  17051  16239.0
1  11491  39002.0
2   7433  21182.0
3  14606   8123.0
4   8381  28282.0

In [9]:
behave.head()

,ID,cc_cons_apr,dc_cons_apr,cc_cons_may,dc_cons_may,cc_cons_jun,dc_cons_jun,cc_count_apr,cc_count_may,cc_count_jun,...,credit_count_may,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active
0,17051,2017.46,29066.66,15919.84,2197.00,3752.000,29798.00,1.0,4,35,...,47,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84
1,11491,7687.00,1308.00,41888.92,2216.92,7060.530,3143.36,2.0,27,50,...,0,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69
2,7433,9094.46,14825.95,3087.64,769.59,25602.595,1445.00,44.0,8,47,...,2,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90
3,14606,3126.00,4616.33,8676.80,5923.00,6717.000,18747.00,4.0,30,1,...,45,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61
4,8381,24988.72,10091.23,10132.00,3477.00,4667.000,511.00,2.0,8,5,...,1,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89

In [10]:
demo.head()

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0
1,11491,current,M,37,LOW,14.4,7,7,485,0
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0
3,14606,current,M,63,LOW,10.2,6,6,863,0
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0

In [11]:
consum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       20000 non-null  int64
 1   cc_cons  15000 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 312.6 KB

In [12]:
behave.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     20000 non-null  int64
 1   cc_cons_apr            20000 non-null  float64
 2   dc_cons_apr            20000 non-null  float64
 3   cc_cons_may            19999 non-null  float64
 4   dc_cons_may            19999 non-null  float64
 5   cc_cons_jun            20000 non-null  float64
 6   dc_cons_jun            19999 non-null  float64
 7   cc_count_apr           19999 non-null  float64
 8   cc_count_may           20000 non-null  int64
 9   cc_count_jun           20000 non-null  int64
 10  dc_count_apr           20000 non-null  int64
 11  dc_count_may           20000 non-null  int64
 12  dc_count_jun           20000 non-null  int64
 13  card_lim               20000 non-null  int64
 14  personal_loan_active   20000 non-null  int64
 15  vehicle_loan_active    20000 non-null  int64
 16  personal_loan_closed   19999 non-null  float64
 17  vehicle_loan_closed    20000 non-null  int64
 18  investment_1           20000 non-null  float64
 19  investment_2           20000 non-null  float64
 20  investment_3           19998 non-null  float64
 21  investment_4           20000 non-null  float64
 22  debit_amount_apr       20000 non-null  float64
 23  credit_amount_apr      20000 non-null  float64
 24  debit_count_apr        19999 non-null  float64
 25  credit_count_apr       20000 non-null  int64
 26  max_credit_amount_apr  20000 non-null  float64
 27  debit_amount_may       20000 non-null  float64
 28  credit_amount_may      20000 non-null  float64
 29  credit_count_may       20000 non-null  int64
 30  debit_count_may        20000 non-null  int64
 31  max_credit_amount_may  20000 non-null  float64
 32  debit_amount_jun       20000 non-null  float64
 33  credit_amount_jun      20000 non-null  float64
 34  credit_count_jun       20000 non-null  int64
 35  debit_count_jun        20000 non-null  int64
 36  max_credit_amount_jun  20000 non-null  float64
 37  loan_enq               19998 non-null  object
 38  emi_active             19999 non-null  float64
dtypes: float64(23), int64(15), object(1)
memory usage: 6.0+ MB

In [14]:
demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            20000 non-null  int64
 1   account_type                  20000 non-null  object
 2   gender                        20000 non-null  object
 3   age                           20000 non-null  int64
 4   Income                        20000 non-null  object
 5   Emp_Tenure_Years              20000 non-null  float64
 6   Tenure_with_Bank              20000 non-null  int64
 7   region_code                   20000 non-null  int64
 8   NetBanking_Flag               20000 non-null  int64
 9   Avg_days_between_transaction  20000 non-null  int64
dtypes: float64(1), int64(6), object(3)
memory usage: 1.5+ MB

In [15]:
df = pd.merge(demo, behave, on = "ID")

In [16]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,credit_count_may,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,47,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,0,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,2,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,45,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,1,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,35,11,32944.0,105488.53,125470.83,21,50,58037.0,Y,7870.88
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,5,8,8850.0,77112.66,86559.00,62,38,24110.0,Y,3668.30
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,10,108,35819.0,57192.48,80627.00,2,18,1769.0,Y,5450.34
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,11,12,39083.0,82039.00,24332.00,117,64,37255.0,Y,59.29
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,7,13,22831.0,60035.50,76669.00,9,64,96213.0,Y,793.41

In [17]:
df = df.merge(consum, on = 'ID')

In [18]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84,16239.0
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69,39002.0
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90,21182.0
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61,8123.0
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89,28282.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,11,32944.0,105488.53,125470.83,21,50,58037.0,Y,7870.88,NaN
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,8,8850.0,77112.66,86559.00,62,38,24110.0,Y,3668.30,NaN
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,108,35819.0,57192.48,80627.00,2,18,1769.0,Y,5450.34,NaN
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,12,39083.0,82039.00,24332.00,117,64,37255.0,Y,59.29,NaN
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,13,22831.0,60035.50,76669.00,9,64,96213.0,Y,793.41,NaN

In [37]:
train = df[df['cc_cons'].notnull()].copy()

In [38]:
test = df[df['cc_cons'].isnull()].copy()

In [21]:
df.shape

(20000, 49)

In [22]:
df.head()

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84,16239.0
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69,39002.0
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90,21182.0
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61,8123.0
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89,28282.0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 49 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            20000 non-null  int64
 1   account_type                  20000 non-null  object
 2   gender                        20000 non-null  object
 3   age                           20000 non-null  int64
 4   Income                        20000 non-null  object
 5   Emp_Tenure_Years              20000 non-null  float64
 6   Tenure_with_Bank              20000 non-null  int64
 7   region_code                   20000 non-null  int64
 8   NetBanking_Flag               20000 non-null  int64
 9   Avg_days_between_transaction  20000 non-null  int64
 10  cc_cons_apr                   20000 non-null  float64
 11  dc_cons_apr                   20000 non-null  float64
 12  cc_cons_may                   19999 non-null  float64
 13  dc_cons_may                   19999 non-null  float64
 14  cc_cons_jun                   20000 non-null  float64
 15  dc_cons_jun                   19999 non-null  float64
 16  cc_count_apr                  19999 non-null  float64
 17  cc_count_may                  20000 non-null  int64
 18  cc_count_jun                  20000 non-null  int64
 19  dc_count_apr                  20000 non-null  int64
 20  dc_count_may                  20000 non-null  int64
 21  dc_count_jun                  20000 non-null  int64
 22  card_lim                      20000 non-null  int64
 23  personal_loan_active          20000 non-null  int64
 24  vehicle_loan_active           20000 non-null  int64
 25  personal_loan_closed          19999 non-null  float64
 26  vehicle_loan_closed           20000 non-null  int64
 27  investment_1                  20000 non-null  float64
 28  investment_2                  20000 non-null  float64
 29  investment_3                  19998 non-null  float64
 30  investment_4                  20000 non-null  float64
 31  debit_amount_apr              20000 non-null  float64
 32  credit_amount_apr             20000 non-null  float64
 33  debit_count_apr               19999 non-null  float64
 34  credit_count_apr              20000 non-null  int64
 35  max_credit_amount_apr         20000 non-null  float64
 36  debit_amount_may              20000 non-null  float64
 37  credit_amount_may             20000 non-null  float64
 38  credit_count_may              20000 non-null  int64
 39  debit_count_may               20000 non-null  int64
 40  max_credit_amount_may         20000 non-null  float64
 41  debit_amount_jun              20000 non-null  float64
 42  credit_amount_jun             20000 non-null  float64
 43  credit_count_jun              20000 non-null  int64
 44  debit_count_jun               20000 non-null  int64
 45  max_credit_amount_jun         20000 non-null  float64
 46  loan_enq                      19998 non-null  object
 47  emi_active                    19999 non-null  float64
 48  cc_cons                       15000 non-null  float64
dtypes: float64(25), int64(20), object(4)
memory usage: 7.5+ MB

In [24]:
df.describe()

,ID,age,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,cc_cons_apr,dc_cons_apr,cc_cons_may,...,credit_count_may,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,emi_active,cc_cons
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,1.999900e+04,...,20000.00000,20000.000000,2.000000e+04,2.000000e+04,2.000000e+04,20000.000000,20000.000000,2.000000e+04,1.999900e+04,15000.000000
mean,9999.500000,47.672300,15.217250,5.496050,5.496050,598.929400,0.718000,17856.990922,8130.453414,1.618836e+04,...,11.91900,40.974850,5.820799e+04,7.812280e+04,7.881693e+04,19.905450,44.529100,5.284985e+04,1.539887e+04,9369.030957
std,5773.647028,30.359771,20.481455,2.870452,2.870452,220.140472,0.449985,25158.878234,14572.188829,2.651068e+04,...,16.85576,40.561202,2.085914e+05,2.448983e+05,1.569872e+05,27.055323,35.080453,1.343175e+05,1.202541e+05,7552.997163
min,0.000000,25.000000,0.500000,1.000000,1.000000,0.000000,0.000000,253.000000,19.350000,1.570000e+02,...,0.00000,0.000000,2.500000e-01,5.230000e+00,1.188000e+01,1.000000,0.000000,6.000000e-02,0.000000e+00,610.099000
25%,4999.750000,33.000000,5.100000,3.000000,3.000000,424.000000,0.000000,4377.000000,1624.650000,3.635910e+03,...,2.00000,11.000000,2.020225e+04,2.576311e+04,2.492008e+04,4.000000,12.000000,1.896450e+04,1.545940e+03,4808.621700
50%,9999.500000,40.000000,9.900000,6.000000,6.000000,623.000000,1.000000,10214.642500,3964.750000,8.635230e+03,...,4.00000,23.000000,3.149650e+04,4.572505e+04,4.618300e+04,7.000000,37.000000,3.025000e+04,3.934660e+03,7408.604400
75%,14999.250000,53.000000,18.000000,8.000000,8.000000,799.000000,1.000000,21189.000000,9339.020000,1.865531e+04,...,11.00000,69.000000,5.642100e+04,8.529653e+04,8.602000e+04,21.000000,73.000000,5.344900e+04,9.376390e+03,11518.832800
max,19999.000000,223.000000,203.000000,10.000000,10.000000,974.000000,1.000000,441031.330000,229255.000000,1.117246e+06,...,71.00000,171.000000,1.000000e+07,2.642915e+07,6.611953e+06,117.000000,133.000000,5.200000e+06,7.447125e+06,160735.934800

In [26]:
num_cols = df.select_dtypes(include= ['float64', 'int64']).columns

In [27]:
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [29]:
df.isnull().sum()

ID                              0
account_type                    0
gender                          0
age                             0
Income                          0
Emp_Tenure_Years                0
Tenure_with_Bank                0
region_code                     0
NetBanking_Flag                 0
Avg_days_between_transaction    0
cc_cons_apr                     0
dc_cons_apr                     0
cc_cons_may                     0
dc_cons_may                     0
cc_cons_jun                     0
dc_cons_jun                     0
cc_count_apr                    0
cc_count_may                    0
cc_count_jun                    0
dc_count_apr                    0
dc_count_may                    0
dc_count_jun                    0
card_lim                        0
personal_loan_active            0
vehicle_loan_active             0
personal_loan_closed            0
vehicle_loan_closed             0
investment_1                    0
investment_2                    0
investment_3                    0
investment_4                    0
debit_amount_apr                0
credit_amount_apr               0
debit_count_apr                 0
credit_count_apr                0
max_credit_amount_apr           0
debit_amount_may                0
credit_amount_may               0
credit_count_may                0
debit_count_may                 0
max_credit_amount_may           0
debit_amount_jun                0
credit_amount_jun               0
credit_count_jun                0
debit_count_jun                 0
max_credit_amount_jun           0
loan_enq                        2
emi_active                      0
cc_cons                         0
dtype: int64

In [30]:
cat_cols = df.select_dtypes(include = ['object']).columns

In [33]:
df[cat_cols] = df[cat_cols].apply(lambda x: x.fillna(x.mode()[0]))

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 49 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            20000 non-null  int64
 1   account_type                  20000 non-null  object
 2   gender                        20000 non-null  object
 3   age                           20000 non-null  int64
 4   Income                        20000 non-null  object
 5   Emp_Tenure_Years              20000 non-null  float64
 6   Tenure_with_Bank              20000 non-null  int64
 7   region_code                   20000 non-null  int64
 8   NetBanking_Flag               20000 non-null  int64
 9   Avg_days_between_transaction  20000 non-null  int64
 10  cc_cons_apr                   20000 non-null  float64
 11  dc_cons_apr                   20000 non-null  float64
 12  cc_cons_may                   20000 non-null  float64
 13  dc_cons_may                   20000 non-null  float64
 14  cc_cons_jun                   20000 non-null  float64
 15  dc_cons_jun                   20000 non-null  float64
 16  cc_count_apr                  20000 non-null  float64
 17  cc_count_may                  20000 non-null  int64
 18  cc_count_jun                  20000 non-null  int64
 19  dc_count_apr                  20000 non-null  int64
 20  dc_count_may                  20000 non-null  int64
 21  dc_count_jun                  20000 non-null  int64
 22  card_lim                      20000 non-null  int64
 23  personal_loan_active          20000 non-null  int64
 24  vehicle_loan_active           20000 non-null  int64
 25  personal_loan_closed          20000 non-null  float64
 26  vehicle_loan_closed           20000 non-null  int64
 27  investment_1                  20000 non-null  float64
 28  investment_2                  20000 non-null  float64
 29  investment_3                  20000 non-null  float64
 30  investment_4                  20000 non-null  float64
 31  debit_amount_apr              20000 non-null  float64
 32  credit_amount_apr             20000 non-null  float64
 33  debit_count_apr               20000 non-null  float64
 34  credit_count_apr              20000 non-null  int64
 35  max_credit_amount_apr         20000 non-null  float64
 36  debit_amount_may              20000 non-null  float64
 37  credit_amount_may             20000 non-null  float64
 38  credit_count_may              20000 non-null  int64
 39  debit_count_may               20000 non-null  int64
 40  max_credit_amount_may         20000 non-null  float64
 41  debit_amount_jun              20000 non-null  float64
 42  credit_amount_jun             20000 non-null  float64
 43  credit_count_jun              20000 non-null  int64
 44  debit_count_jun               20000 non-null  int64
 45  max_credit_amount_jun         20000 non-null  float64
 46  loan_enq                      20000 non-null  object
 47  emi_active                    20000 non-null  float64
 48  cc_cons                       20000 non-null  float64
dtypes: float64(25), int64(20), object(4)
memory usage: 7.5+ MB

In [36]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,debit_count_may,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,20,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84,16239.0000
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,8,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69,39002.0000
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,14,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90,21182.0000
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,44,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61,8123.0000
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,2,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89,28282.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,11,32944.0,105488.53,125470.83,21,50,58037.0,Y,7870.88,7408.6044
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,8,8850.0,77112.66,86559.00,62,38,24110.0,Y,3668.30,7408.6044
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,108,35819.0,57192.48,80627.00,2,18,1769.0,Y,5450.34,7408.6044
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,12,39083.0,82039.00,24332.00,117,64,37255.0,Y,59.29,7408.6044
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,13,22831.0,60035.50,76669.00,9,64,96213.0,Y,793.41,7408.6044

In [40]:
df['total_cc_spend'] = df['cc_cons_apr'] + df['cc_cons_may'] + df['cc_cons_jun']

In [41]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,max_credit_amount_may,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons,total_cc_spend
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,41860.0,32734.75,80959.00,36,9,171200.0,Y,3448.84,16239.0000,21689.300
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,113367.0,60974.75,495080.00,5,3,15694.0,Y,3812.69,39002.0000,56636.450
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,168000.0,425802.96,115707.38,7,58,28058.0,Y,9432.90,21182.0000,37784.695
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,57750.0,25537.91,63606.00,12,0,24459.0,Y,144.61,8123.0000,18519.800
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,18405.0,64687.32,62353.35,49,35,31574.0,Y,1887.89,28282.0000,39787.720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,32944.0,105488.53,125470.83,21,50,58037.0,Y,7870.88,7408.6044,52393.110
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,8850.0,77112.66,86559.00,62,38,24110.0,Y,3668.30,7408.6044,29249.450
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,35819.0,57192.48,80627.00,2,18,1769.0,Y,5450.34,7408.6044,14727.395
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,39083.0,82039.00,24332.00,117,64,37255.0,Y,59.29,7408.6044,40199.260
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,22831.0,60035.50,76669.00,9,64,96213.0,Y,793.41,7408.6044,30364.640

In [42]:
df['total_dc_spend'] = df['dc_cons_apr'] + df['dc_cons_may'] + df['dc_cons_jun']

In [43]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,debit_amount_jun,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons,total_cc_spend,total_dc_spend
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,32734.75,80959.00,36,9,171200.0,Y,3448.84,16239.0000,21689.300,61061.66
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,60974.75,495080.00,5,3,15694.0,Y,3812.69,39002.0000,56636.450,6668.28
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,425802.96,115707.38,7,58,28058.0,Y,9432.90,21182.0000,37784.695,17040.54
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,25537.91,63606.00,12,0,24459.0,Y,144.61,8123.0000,18519.800,29286.33
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,64687.32,62353.35,49,35,31574.0,Y,1887.89,28282.0000,39787.720,14079.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,105488.53,125470.83,21,50,58037.0,Y,7870.88,7408.6044,52393.110,12273.58
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,77112.66,86559.00,62,38,24110.0,Y,3668.30,7408.6044,29249.450,9684.10
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,57192.48,80627.00,2,18,1769.0,Y,5450.34,7408.6044,14727.395,16058.04
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,82039.00,24332.00,117,64,37255.0,Y,59.29,7408.6044,40199.260,43061.00
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,60035.50,76669.00,9,64,96213.0,Y,793.41,7408.6044,30364.640,22612.00

In [44]:
df['avg_cc_spend'] = df['total_cc_spend']/3

In [45]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons,total_cc_spend,total_dc_spend,avg_cc_spend
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,80959.00,36,9,171200.0,Y,3448.84,16239.0000,21689.300,61061.66,7229.766667
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,495080.00,5,3,15694.0,Y,3812.69,39002.0000,56636.450,6668.28,18878.816667
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,115707.38,7,58,28058.0,Y,9432.90,21182.0000,37784.695,17040.54,12594.898333
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,63606.00,12,0,24459.0,Y,144.61,8123.0000,18519.800,29286.33,6173.266667
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,62353.35,49,35,31574.0,Y,1887.89,28282.0000,39787.720,14079.23,13262.573333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,125470.83,21,50,58037.0,Y,7870.88,7408.6044,52393.110,12273.58,17464.370000
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,86559.00,62,38,24110.0,Y,3668.30,7408.6044,29249.450,9684.10,9749.816667
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,80627.00,2,18,1769.0,Y,5450.34,7408.6044,14727.395,16058.04,4909.131667
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,24332.00,117,64,37255.0,Y,59.29,7408.6044,40199.260,43061.00,13399.753333
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,76669.00,9,64,96213.0,Y,793.41,7408.6044,30364.640,22612.00,10121.546667

In [46]:
df['spend_to_limit_ratio'] = df['total_cc_spend'] / (df['card_lim'] + 1)

In [47]:
df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons,total_cc_spend,total_dc_spend,avg_cc_spend,spend_to_limit_ratio
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,36,9,171200.0,Y,3448.84,16239.0000,21689.300,61061.66,7229.766667,0.062867
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,5,3,15694.0,Y,3812.69,39002.0000,56636.450,6668.28,18878.816667,0.153486
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,7,58,28058.0,Y,9432.90,21182.0000,37784.695,17040.54,12594.898333,1.399381
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,12,0,24459.0,Y,144.61,8123.0000,18519.800,29286.33,6173.266667,0.094973
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,49,35,31574.0,Y,1887.89,28282.0000,39787.720,14079.23,13262.573333,0.846529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,21,50,58037.0,Y,7870.88,7408.6044,52393.110,12273.58,17464.370000,0.088055
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,62,38,24110.0,Y,3668.30,7408.6044,29249.450,9684.10,9749.816667,2.249785
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,2,18,1769.0,Y,5450.34,7408.6044,14727.395,16058.04,4909.131667,0.118768
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,117,64,37255.0,Y,59.29,7408.6044,40199.260,43061.00,13399.753333,0.108354
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,9,64,96213.0,Y,793.41,7408.6044,30364.640,22612.00,10121.546667,0.052716

In [50]:
df = pd.get_dummies(df, drop_first=True)

In [51]:
df

,ID,age,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,cc_cons_apr,dc_cons_apr,cc_cons_may,...,total_dc_spend,avg_cc_spend,spend_to_limit_ratio,account_type_current,account_type_saving,gender_F,gender_M,Income_HIGH,Income_LOW,Income_MEDIUM
0,17051,30,26.4,9,9,355,0,2017.460,29066.66,15919.84,...,61061.66,7229.766667,0.062867,True,False,False,True,False,False,True
1,11491,37,14.4,7,7,485,0,7687.000,1308.00,41888.92,...,6668.28,18878.816667,0.153486,True,False,False,True,False,True,False
2,7433,33,3.2,1,1,764,0,9094.460,14825.95,3087.64,...,17040.54,12594.898333,1.399381,True,False,False,True,False,False,True
3,14606,63,10.2,6,6,863,0,3126.000,4616.33,8676.80,...,29286.33,6173.266667,0.094973,True,False,False,True,False,True,False
4,8381,33,26.4,6,6,523,0,24988.720,10091.23,10132.00,...,14079.23,13262.573333,0.846529,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,35,13.5,1,1,523,0,4641.500,5979.58,6008.61,...,12273.58,17464.370000,0.088055,True,False,False,True,False,False,True
19996,14224,53,9.9,7,7,723,1,4994.450,2805.37,23214.00,...,9684.10,9749.816667,2.249785,True,False,False,True,False,False,True
19997,18740,62,37.8,8,8,863,1,3262.145,2871.00,7335.25,...,16058.04,4909.131667,0.118768,True,False,False,True,True,False,False
19998,18134,34,12.6,4,4,882,0,12824.010,4866.00,12242.48,...,43061.00,13399.753333,0.108354,True,False,False,True,False,False,True
19999,12413,27,3.5,8,8,447,1,26218.000,6615.00,2832.00,...,22612.00,10121.546667,0.052716,True,False,False,True,False,True,False

In [53]:
df = df.drop(['account_type_saving', 'gender_M', 'Income_LOW'], axis=1)

In [54]:
df

,ID,age,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,cc_cons_apr,dc_cons_apr,cc_cons_may,...,emi_active,cc_cons,total_cc_spend,total_dc_spend,avg_cc_spend,spend_to_limit_ratio,account_type_current,gender_F,Income_HIGH,Income_MEDIUM
0,17051,30,26.4,9,9,355,0,2017.460,29066.66,15919.84,...,3448.84,16239.0000,21689.300,61061.66,7229.766667,0.062867,True,False,False,True
1,11491,37,14.4,7,7,485,0,7687.000,1308.00,41888.92,...,3812.69,39002.0000,56636.450,6668.28,18878.816667,0.153486,True,False,False,False
2,7433,33,3.2,1,1,764,0,9094.460,14825.95,3087.64,...,9432.90,21182.0000,37784.695,17040.54,12594.898333,1.399381,True,False,False,True
3,14606,63,10.2,6,6,863,0,3126.000,4616.33,8676.80,...,144.61,8123.0000,18519.800,29286.33,6173.266667,0.094973,True,False,False,False
4,8381,33,26.4,6,6,523,0,24988.720,10091.23,10132.00,...,1887.89,28282.0000,39787.720,14079.23,13262.573333,0.846529,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,35,13.5,1,1,523,0,4641.500,5979.58,6008.61,...,7870.88,7408.6044,52393.110,12273.58,17464.370000,0.088055,True,False,False,True
19996,14224,53,9.9,7,7,723,1,4994.450,2805.37,23214.00,...,3668.30,7408.6044,29249.450,9684.10,9749.816667,2.249785,True,False,False,True
19997,18740,62,37.8,8,8,863,1,3262.145,2871.00,7335.25,...,5450.34,7408.6044,14727.395,16058.04,4909.131667,0.118768,True,False,True,False
19998,18134,34,12.6,4,4,882,0,12824.010,4866.00,12242.48,...,59.29,7408.6044,40199.260,43061.00,13399.753333,0.108354,True,False,False,True
19999,12413,27,3.5,8,8,447,1,26218.000,6615.00,2832.00,...,793.41,7408.6044,30364.640,22612.00,10121.546667,0.052716,True,False,False,False